/**
 * Engine Configuration
 *
 * Defines all 14 page engines for the Senior Benefits Care Finder site.
 * Each engine specifies its template, URL pattern, SEO patterns, data schema,
 * schema.org type, and related engines for cross-linking.
 */

const engines = [

  // -----------------------------------------------------------------------
  // ENGINE 1: Medicare Plans Hub
  // -----------------------------------------------------------------------
  {
    id: 'medicare',
    name: 'Medicare Plans Hub',
    template: 'medicare-plans',
    category: 'medicare',
    categoryLabel: 'Medicare',
    scope: 'state',
    urlPattern: '/medicare/[stateSlug]',
    seoTitle: 'Medicare Plans in [state] ([currentYear]) – Advantage, Medigap & Part D',
    metaDescription: 'Compare Medicare Advantage, Medigap, and Part D plans available in [state]. See [currentYear] costs, coverage options, eligibility, and enrollment periods.',
    schemaType: 'Article',
    relatedEngines: ['medicaid', 'prescription-assistance', 'comparison'],
    dataSchema: {
      stateSlug: 'string — URL slug for the state',
      state: 'string — full state name',
      stateAbbr: 'string — two-letter abbreviation',
      h1: 'string — main page heading',
      introText: 'string — opening paragraph (HTML allowed)',
      advantagePlans: 'number — count of MA plans available',
      medigapPlans: 'number — count of Medigap plans',
      partDPlans: 'number — count of Part D plans',
      avgPremiumMA: 'string — avg monthly premium for MA',
      avgPremiumMedigap: 'string — avg monthly premium for Medigap',
      avgPremiumPartD: 'string — avg monthly premium for Part D',
      enrollmentPeriods: 'array — [{name, startDate, endDate, description}]',
      eligibilityAge: 'number — default 65',
      specialPrograms: 'array — [{name, description, url}]',
      localResources: 'array — [{name, phone, url, description}]',
      faqs: 'array — [{question, answer}]',
      sources: 'array — [{title, url}]',
    },
  },

  // -----------------------------------------------------------------------
  // ENGINE 2: Medicaid Eligibility
  // -----------------------------------------------------------------------
  {
    id: 'medicaid',
    name: 'Medicaid Eligibility',
    template: 'medicaid-eligibility',
    category: 'medicaid',
    categoryLabel: 'Medicaid',
    scope: 'state',
    urlPattern: '/medicaid/eligibility/[stateSlug]',
    seoTitle: 'Medicaid Eligibility in [state] ([currentYear]) – Income Limits & How to Apply',
    metaDescription: 'Check [currentYear] Medicaid eligibility in [state]. See income limits, asset requirements, application process, and available programs for seniors.',
    schemaType: 'Article',
    relatedEngines: ['medicare', 'low-income-programs', 'prescription-assistance'],
    dataSchema: {
      stateSlug: 'string',
      state: 'string',
      stateAbbr: 'string',
      h1: 'string',
      introText: 'string (HTML)',
      programName: 'string — state-specific Medicaid program name (e.g., Medi-Cal)',
      expansionStatus: 'string — "expanded" or "not expanded"',
      incomeLimit: {
        individual: 'string — monthly income limit',
        couple: 'string — monthly income limit for couples',
        fpl: 'string — Federal Poverty Level percentage',
      },
      assetLimit: {
        individual: 'string',
        couple: 'string',
        exemptions: 'array — [string] list of exempt assets',
      },
      applicationMethods: 'array — [{method, description, url}]',
      requiredDocuments: 'array — [string]',
      programs: 'array — [{name, description, eligibility, url}]',
      waiverPrograms: 'array — [{name, description, url}]',
      managedCare: 'boolean — does state use managed care',
      managedCarePlans: 'array — [{name, description}]',
      processingTime: 'string — typical processing time',
      faqs: 'array — [{question, answer}]',
      sources: 'array — [{title, url}]',
    },
  },

  // -----------------------------------------------------------------------
  // ENGINE 3: Assisted Living Cost
  // -----------------------------------------------------------------------
  {
    id: 'assisted-living',
    name: 'Assisted Living Cost',
    template: 'assisted-living-cost',
    category: 'assisted-living',
    categoryLabel: 'Assisted Living',
    scope: 'state+city',
    urlPattern: '/assisted-living/cost/[stateSlug]',
    cityUrlPattern: '/assisted-living/cost/[stateSlug]/[citySlug]',
    seoTitle: 'Assisted Living Cost in [state] ([currentYear]) – Monthly Prices & Options',
    metaDescription: 'See [currentYear] assisted living costs in [state]. Compare monthly prices by care level, explore payment options, and find facilities near you.',
    schemaType: 'Article',
    relatedEngines: ['home-care', 'long-term-care', 'provider-directory', 'medicaid'],
    dataSchema: {
      stateSlug: 'string',
      state: 'string',
      stateAbbr: 'string',
      citySlug: 'string (optional — for city-level pages)',
      city: 'string (optional)',
      h1: 'string',
      introText: 'string (HTML)',
      avgMonthlyCost: 'string — state/city average',
      costRange: { min: 'string', max: 'string' },
      nationalAvg: 'string — national average for comparison',
      costByLevel: 'array — [{level, monthlyCost, description}]',
      includedServices: 'array — [string]',
      additionalCosts: 'array — [{service, cost}]',
      paymentOptions: 'array — [{method, description, eligible}]',
      memoryCare: { avgCost: 'string', description: 'string' },
      nearbyFacilities: 'array — [{name, address, rating, costRange, url}]',
      costTrend: 'string — year-over-year trend',
      faqs: 'array — [{question, answer}]',
      sources: 'array — [{title, url}]',
    },
  },

  // -----------------------------------------------------------------------
  // ENGINE 4: Social Security & SSI
  // -----------------------------------------------------------------------
  {
    id: 'social-security',
    name: 'Social Security & SSI',
    template: 'social-security',
    category: 'social-security',
    categoryLabel: 'Social Security',
    scope: 'state',
    urlPattern: '/social-security/[stateSlug]',
    seoTitle: 'Social Security & SSI Benefits in [state] ([currentYear]) – Amounts & Eligibility',
    metaDescription: 'Learn about Social Security retirement, SSDI, and SSI benefits in [state]. See [currentYear] benefit amounts, eligibility rules, and how to apply.',
    schemaType: 'Article',
    relatedEngines: ['medicaid', 'low-income-programs', 'disability-benefits'],
    dataSchema: {
      stateSlug: 'string',
      state: 'string',
      stateAbbr: 'string',
      h1: 'string',
      introText: 'string (HTML)',
      avgRetirementBenefit: 'string — state avg monthly benefit',
      maxRetirementBenefit: 'string — maximum at full retirement age',
      ssiSupplement: 'string — state SSI supplement amount (if any)',
      hasSsiSupplement: 'boolean',
      fullRetirementAge: 'string',
      earlyRetirementAge: 'string — 62',
      cola: 'string — current year COLA adjustment',
      ssdiAvgBenefit: 'string — avg SSDI monthly benefit',
      ssiMaxBenefit: { individual: 'string', couple: 'string' },
      localOffices: 'array — [{name, address, phone, hours}]',
      applicationMethods: 'array — [{method, description, url}]',
      taxInfo: 'string — does state tax SS benefits',
      faqs: 'array — [{question, answer}]',
      sources: 'array — [{title, url}]',
    },
  },

  // -----------------------------------------------------------------------
  // ENGINE 5: Home Care
  // -----------------------------------------------------------------------
  {
    id: 'home-care',
    name: 'Home Care Cost & Options',
    template: 'home-care',
    category: 'home-care',
    categoryLabel: 'Home Care',
    scope: 'state+city',
    urlPattern: '/home-care/cost/[stateSlug]',
    cityUrlPattern: '/home-care/cost/[stateSlug]/[citySlug]',
    seoTitle: 'Home Care Cost in [state] ([currentYear]) – In-Home Care Rates & Options',
    metaDescription: 'See [currentYear] home care costs in [state]. Compare hourly rates for in-home caregivers, home health aides, and skilled nursing. Find local agencies.',
    schemaType: 'Article',
    relatedEngines: ['assisted-living', 'medicaid', 'veterans-benefits', 'long-term-care'],
    dataSchema: {
      stateSlug: 'string',
      state: 'string',
      stateAbbr: 'string',
      citySlug: 'string (optional)',
      city: 'string (optional)',
      h1: 'string',
      introText: 'string (HTML)',
      avgHourlyCost: 'string',
      avgMonthlyCost: 'string — based on 44hrs/week',
      nationalAvgHourly: 'string',
      costByType: 'array — [{type, hourlyCost, monthlyCost, description}]',
      careTypes: 'array — [{name, description, typicalTasks}]',
      paymentOptions: 'array — [{method, description, eligible}]',
      medicaidCoverage: 'string — description of Medicaid home care coverage',
      localAgencies: 'array — [{name, phone, url, rating}]',
      howToChoose: 'array — [{step, title, description}]',
      faqs: 'array — [{question, answer}]',
      sources: 'array — [{title, url}]',
    },
  },

  // -----------------------------------------------------------------------
  // ENGINE 6: Prescription Assistance
  // -----------------------------------------------------------------------
  {
    id: 'prescription-assistance',
    name: 'Prescription Assistance',
    template: 'prescription-assistance',
    category: 'prescription-assistance',
    categoryLabel: 'Prescription Assistance',
    scope: 'state',
    urlPattern: '/prescription-assistance/[stateSlug]',
    seoTitle: 'Prescription Assistance Programs in [state] ([currentYear]) – Drug Cost Help',
    metaDescription: 'Find prescription assistance programs in [state]. Learn about Medicare Extra Help, state pharmaceutical programs, and patient assistance to lower drug costs.',
    schemaType: 'Article',
    relatedEngines: ['medicare', 'medicaid', 'low-income-programs'],
    dataSchema: {
      stateSlug: 'string',
      state: 'string',
      stateAbbr: 'string',
      h1: 'string',
      introText: 'string (HTML)',
      hasStateSPAP: 'boolean — does state have a SPAP',
      spapName: 'string — state pharmaceutical assistance program name',
      spapDescription: 'string',
      spapEligibility: 'string',
      spapUrl: 'string',
      extraHelpIncomeLimits: { individual: 'string', couple: 'string' },
      extraHelpAssetLimits: { individual: 'string', couple: 'string' },
      programs: 'array — [{name, type, eligibility, description, url, phone}]',
      discountPrograms: 'array — [{name, savings, description, url}]',
      applicationSteps: 'array — [{step, title, description}]',
      faqs: 'array — [{question, answer}]',
      sources: 'array — [{title, url}]',
    },
  },

  // -----------------------------------------------------------------------
  // ENGINE 7: Veterans Benefits
  // -----------------------------------------------------------------------
  {
    id: 'veterans-benefits',
    name: 'Veterans Benefits',
    template: 'veterans-benefits',
    category: 'veterans-benefits',
    categoryLabel: 'Veterans Benefits',
    scope: 'state',
    urlPattern: '/veterans-benefits/[stateSlug]',
    seoTitle: 'Veterans Benefits in [state] ([currentYear]) – VA & State Programs for Seniors',
    metaDescription: 'Explore federal VA and [state] state veterans benefits for seniors. See Aid & Attendance, pension, health care, and state-specific programs.',
    schemaType: 'Article',
    relatedEngines: ['medicare', 'home-care', 'assisted-living', 'disability-benefits'],
    dataSchema: {
      stateSlug: 'string',
      state: 'string',
      stateAbbr: 'string',
      h1: 'string',
      introText: 'string (HTML)',
      vaFacilities: 'array — [{name, type, address, phone, url}]',
      aidAndAttendance: { maxBenefit: 'string', eligibility: 'string', description: 'string' },
      vaPension: { maxBenefit: 'string', eligibility: 'string', description: 'string' },
      stateBenefits: 'array — [{name, description, eligibility, url}]',
      propertyTaxExemption: 'string — description of state property tax exemption',
      stateVeteransHome: 'array — [{name, location, beds, phone}]',
      caregiverSupport: 'array — [{program, description, url}]',
      applicationSteps: 'array — [{step, title, description}]',
      faqs: 'array — [{question, answer}]',
      sources: 'array — [{title, url}]',
    },
  },

  // -----------------------------------------------------------------------
  // ENGINE 8: Comparison & Decision
  // -----------------------------------------------------------------------
  {
    id: 'comparison',
    name: 'Comparison & Decision',
    template: 'comparison',
    category: 'compare',
    categoryLabel: 'Compare Options',
    scope: 'topic',
    urlPattern: '/compare/[slug]',
    seoTitle: '[title] – Side-by-Side Comparison ([currentYear])',
    metaDescription: '[metaDescription]',
    schemaType: 'Article',
    relatedEngines: ['medicare', 'assisted-living', 'home-care', 'medicaid'],
    dataSchema: {
      slug: 'string — URL slug',
      h1: 'string',
      title: 'string — for SEO title',
      introText: 'string (HTML)',
      optionA: { name: 'string', description: 'string' },
      optionB: { name: 'string', description: 'string' },
      comparisonRows: 'array — [{category, optionAValue, optionBValue}]',
      prosConsA: { pros: ['string'], cons: ['string'] },
      prosConsB: { pros: ['string'], cons: ['string'] },
      whoShouldChooseA: 'string',
      whoShouldChooseB: 'string',
      costComparison: { optionACost: 'string', optionBCost: 'string', description: 'string' },
      bottomLine: 'string (HTML)',
      faqs: 'array — [{question, answer}]',
      sources: 'array — [{title, url}]',
    },
  },

  // -----------------------------------------------------------------------
  // ENGINE 9: Low-Income Senior Programs
  // -----------------------------------------------------------------------
  {
    id: 'low-income-programs',
    name: 'Low-Income Senior Programs',
    template: 'low-income-programs',
    category: 'low-income-programs',
    categoryLabel: 'Low-Income Programs',
    scope: 'state',
    urlPattern: '/low-income-programs/[stateSlug]',
    seoTitle: 'Low-Income Senior Programs in [state] ([currentYear]) – Benefits & Assistance',
    metaDescription: 'Find low-income assistance programs for seniors in [state]. See SNAP, LIHEAP, housing assistance, phone discounts, and transportation programs.',
    schemaType: 'Article',
    relatedEngines: ['medicaid', 'social-security', 'prescription-assistance'],
    dataSchema: {
      stateSlug: 'string',
      state: 'string',
      stateAbbr: 'string',
      h1: 'string',
      introText: 'string (HTML)',
      programs: 'array — [{name, category, description, eligibility, benefits, applicationUrl, phone}]',
      snapInfo: { incomeLimitIndividual: 'string', maxBenefit: 'string', applicationUrl: 'string' },
      liheapInfo: { maxBenefit: 'string', applicationPeriod: 'string', url: 'string' },
      housingInfo: { programs: ['string'], waitlistInfo: 'string', url: 'string' },
      lifelineInfo: { discount: 'string', eligibility: 'string', url: 'string' },
      propertyTaxRelief: { available: 'boolean', description: 'string', url: 'string' },
      transportationPrograms: 'array — [{name, description, url}]',
      faqs: 'array — [{question, answer}]',
      sources: 'array — [{title, url}]',
    },
  },

  // -----------------------------------------------------------------------
  // ENGINE 10: Disability & Condition-Specific Benefits
  // -----------------------------------------------------------------------
  {
    id: 'disability-benefits',
    name: 'Disability & Condition-Specific Benefits',
    template: 'disability-benefits',
    category: 'disability-benefits',
    categoryLabel: 'Disability Benefits',
    scope: 'condition',
    urlPattern: '/disability-benefits/[slug]',
    stateUrlPattern: '/disability-benefits/[slug]/[stateSlug]',
    seoTitle: 'Benefits for Seniors with [condition] ([currentYear]) – Programs & Support',
    metaDescription: 'Find benefits and support programs for seniors with [condition]. See eligibility, application process, financial assistance, and caregiving resources.',
    schemaType: 'Article',
    relatedEngines: ['social-security', 'medicaid', 'veterans-benefits', 'home-care'],
    dataSchema: {
      slug: 'string — condition URL slug',
      condition: 'string — condition name (e.g., "Alzheimer\'s Disease")',
      h1: 'string',
      introText: 'string (HTML)',
      overview: 'string (HTML) — condition overview for seniors',
      prevalence: 'string — how many seniors affected',
      federalPrograms: 'array — [{name, description, eligibility, benefits, url}]',
      medicaidCoverage: 'string (HTML)',
      medicareCoverage: 'string (HTML)',
      vaBenefits: 'string (HTML)',
      caregiverResources: 'array — [{name, description, url}]',
      supportOrganizations: 'array — [{name, description, phone, url}]',
      financialAssistance: 'array — [{program, amount, eligibility, url}]',
      dailyLivingAids: 'array — [{name, description, cost}]',
      faqs: 'array — [{question, answer}]',
      sources: 'array — [{title, url}]',
    },
  },

  // -----------------------------------------------------------------------
  // ENGINE 11: Long-Term Care Insurance & Planning
  // -----------------------------------------------------------------------
  {
    id: 'long-term-care',
    name: 'Long-Term Care Insurance & Planning',
    template: 'long-term-care',
    category: 'long-term-care',
    categoryLabel: 'Long-Term Care',
    scope: 'state',
    urlPattern: '/long-term-care/[stateSlug]',
    seoTitle: 'Long-Term Care Insurance in [state] ([currentYear]) – Costs & Planning Guide',
    metaDescription: 'Compare long-term care insurance costs in [state]. See [currentYear] premiums by age, coverage options, alternatives, and Medicaid planning strategies.',
    schemaType: 'Article',
    relatedEngines: ['assisted-living', 'home-care', 'medicaid', 'senior-legal'],
    dataSchema: {
      stateSlug: 'string',
      state: 'string',
      stateAbbr: 'string',
      h1: 'string',
      introText: 'string (HTML)',
      avgAnnualPremium: { age55: 'string', age60: 'string', age65: 'string', couple65: 'string' },
      avgLtcCosts: { nursingHome: 'string', assistedLiving: 'string', homeCare: 'string' },
      coverageOptions: 'array — [{type, description, avgPremium, pros, cons}]',
      partnershipProgram: { available: 'boolean', description: 'string' },
      medicaidSpendDown: { assetLimit: 'string', lookbackPeriod: 'string', description: 'string' },
      hybridOptions: 'array — [{type, description, pros, cons}]',
      planningSteps: 'array — [{step, title, description}]',
      faqs: 'array — [{question, answer}]',
      sources: 'array — [{title, url}]',
    },
  },

  // -----------------------------------------------------------------------
  // ENGINE 12: Senior Legal & Financial
  // -----------------------------------------------------------------------
  {
    id: 'senior-legal',
    name: 'Senior Legal & Financial',
    template: 'senior-legal',
    category: 'senior-legal',
    categoryLabel: 'Senior Legal',
    scope: 'state',
    urlPattern: '/senior-legal/[stateSlug]',
    seoTitle: 'Senior Legal Resources in [state] ([currentYear]) – Elder Law & Financial Planning',
    metaDescription: 'Find elder law resources in [state]. Learn about power of attorney, guardianship, estate planning, elder abuse reporting, and senior financial protections.',
    schemaType: 'Article',
    relatedEngines: ['long-term-care', 'medicaid', 'social-security'],
    dataSchema: {
      stateSlug: 'string',
      state: 'string',
      stateAbbr: 'string',
      h1: 'string',
      introText: 'string (HTML)',
      poaLaws: { types: 'array — [string]', description: 'string', formUrl: 'string' },
      guardianship: { process: 'string', description: 'string', courtUrl: 'string' },
      estatePlanning: { description: 'string', requirements: 'array — [string]' },
      elderAbuse: { reportingHotline: 'string', reportingUrl: 'string', laws: 'string' },
      reverseMortgage: { description: 'string', requirements: 'array — [string]', warnings: 'array — [string]' },
      fraudProtection: { resources: 'array — [{name, description, url}]' },
      legalAidOrgs: 'array — [{name, phone, url, services}]',
      faqs: 'array — [{question, answer}]',
      sources: 'array — [{title, url}]',
    },
  },

  // -----------------------------------------------------------------------
  // ENGINE 13: Provider & Facility Directory
  // -----------------------------------------------------------------------
  {
    id: 'provider-directory',
    name: 'Provider & Facility Directory',
    template: 'provider-directory',
    category: 'providers',
    categoryLabel: 'Find Providers',
    scope: 'state+city',
    urlPattern: '/providers/[providerType]/[stateSlug]',
    cityUrlPattern: '/providers/[providerType]/[stateSlug]/[citySlug]',
    seoTitle: 'Best [providerTypeLabel] in [state] ([currentYear]) – Ratings & Reviews',
    metaDescription: 'Find top-rated [providerTypeLabel] in [state]. Compare quality ratings, costs, services, and reviews to choose the best care option.',
    schemaType: 'Article',
    relatedEngines: ['assisted-living', 'home-care', 'long-term-care'],
    dataSchema: {
      stateSlug: 'string',
      state: 'string',
      stateAbbr: 'string',
      citySlug: 'string (optional)',
      city: 'string (optional)',
      providerType: 'string — slug (e.g., "nursing-homes")',
      providerTypeLabel: 'string — display name (e.g., "Nursing Homes")',
      h1: 'string',
      introText: 'string (HTML)',
      providers: 'array — [{name, address, city, phone, rating, ratingSource, specialties, costRange, url}]',
      totalProviders: 'number',
      avgRating: 'string',
      qualityMetrics: 'array — [{metric, description}]',
      howToChoose: 'array — [{step, title, description}]',
      questionsToAsk: 'array — [string]',
      paymentAccepted: 'array — [string]',
      faqs: 'array — [{question, answer}]',
      sources: 'array — [{title, url}]',
    },
  },

  // -----------------------------------------------------------------------
  // ENGINE 14: Authority Pages
  // -----------------------------------------------------------------------
  {
    id: 'authority-page',
    name: 'Authority & Trust Pages',
    template: 'authority-page',
    category: '',
    categoryLabel: '',
    scope: 'standalone',
    urlPattern: '/[slug]',
    seoTitle: '[title] – Senior Benefits Care Finder',
    metaDescription: '[metaDescription]',
    schemaType: 'WebPage',
    relatedEngines: [],
    dataSchema: {
      slug: 'string',
      h1: 'string',
      title: 'string — for SEO title pattern',
      introText: 'string (HTML)',
      sections: 'array — [{heading, content (HTML), icon}]',
      teamMembers: 'array — [{name, role, credentials, bio}] (optional)',
      contactInfo: '{ email, phone, address } (optional)',
      policyContent: 'string (HTML) — for legal/policy pages (optional)',
    },
  },
];

module.exports = { engines };
